version: '3.3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './srv/gitlab/config:/etc/gitlab'
      - './srv/gitlab/logs:/var/log/gitlab'
      - './srv/gitlab/data:/var/opt/gitlab'
    networks:
        - gitlab-line

  php:
    image: 'php:7.2-apache'
    ports:
      - '8001:80'
    volumes:
      - './service:/var/www/html/'
    networks:
      - gitlab-line

networks:
  gitlab-line: